class_name GGModel
extends RefCounted

var document_name: String = "Untitled.ggb"
var units: String = "mm"
var is_dirty: bool = false

var points: Array[GGPoint2D] = []
var next_point_id: int = 1

var lines: Array[GGLine2D] = []
var next_line_id: int = 1


func reset() -> void:
	document_name = "Untitled.ggb"
	units = "mm"
	is_dirty = false
	points.clear()
	next_point_id = 1
	lines.clear()
	next_line_id = 1


# -----------------------------------------------------------------------------
# Points management
# -----------------------------------------------------------------------------

func get_point_by_id(point_id: int) -> GGPoint2D:
	for point: GGPoint2D in points:
		if point.id == point_id:
			return point
	return null


func add_point(x: float, y: float) -> GGPoint2D:
	var point: GGPoint2D = GGPoint2D.new(next_point_id, x, y)
	points.append(point)
	next_point_id += 1
	is_dirty = true
	return point


func clear_points() -> bool:
	if not lines.is_empty():
		return false
	points.clear()
	next_point_id = 1
	is_dirty = true
	return true


func move_point(point_id: int, x: float, y: float) -> bool:
	var point: GGPoint2D = get_point_by_id(point_id)
	if point != null:
		point.x = x
		point.y = y
		is_dirty = true
		return true
	return false


func remove_point(point_id: int) -> bool:
	if is_point_used(point_id):
		return false

	for index: int in range(points.size()):
		if points[index].id == point_id:
			points.remove_at(index)
			is_dirty = true
			return true
	return false


# -----------------------------------------------------------------------------
# Topology inspection
# -----------------------------------------------------------------------------

func get_lines_referencing_point(point_id: int) -> Array[int]:
	var referencing_line_ids: Array[int] = []
	for line: GGLine2D in lines:
		if line.start_point_id == point_id or line.end_point_id == point_id:
			referencing_line_ids.append(line.id)
	return referencing_line_ids


func is_point_used(point_id: int) -> bool:
	for line: GGLine2D in lines:
		if line.start_point_id == point_id or line.end_point_id == point_id:
			return true
	return false


func validate_topology() -> Array[String]:
	var errors: Array[String] = []
	for line: GGLine2D in lines:
		if line.start_point_id == line.end_point_id:
			errors.append("Line %d is degenerate (identical endpoints: %d)." % [line.id, line.start_point_id])
		if get_point_by_id(line.start_point_id) == null:
			errors.append("Line %d references missing start Point %d." % [line.id, line.start_point_id])
		if get_point_by_id(line.end_point_id) == null:
			errors.append("Line %d references missing end Point %d." % [line.id, line.end_point_id])
	return errors


# -----------------------------------------------------------------------------
# Lines management
# -----------------------------------------------------------------------------

func get_line_by_id(line_id: int) -> GGLine2D:
	for line: GGLine2D in lines:
		if line.id == line_id:
			return line
	return null


func add_line(start_id: int, end_id: int) -> GGLine2D:
	if start_id == end_id:
		return null
	if get_point_by_id(start_id) == null or get_point_by_id(end_id) == null:
		return null

	var line: GGLine2D = GGLine2D.new(next_line_id, start_id, end_id)
	lines.append(line)
	next_line_id += 1
	is_dirty = true
	return line


func remove_line(line_id: int) -> bool:
	for index: int in range(lines.size()):
		if lines[index].id == line_id:
			lines.remove_at(index)
			is_dirty = true
			return true
	return false


func clear_lines() -> void:
	lines.clear()
	next_line_id = 1
	is_dirty = true


func rename_document(new_name: String) -> void:
	document_name = new_name + ".ggb"
	is_dirty = true


# -----------------------------------------------------------------------------
# Gmsh .geo Export
# -----------------------------------------------------------------------------

func export_geo_file(target_filename: String) -> bool:
	var path: String = "user://" + target_filename + ".geo"
	var file: FileAccess = FileAccess.open(path, FileAccess.WRITE)
	if file == null:
		return false

	file.store_line("// Generated by GG CAD")
	file.store_line("// Model: " + document_name)
	file.store_line("")

	file.store_line("// Points")
	for point: GGPoint2D in points:
		file.store_line("Point(%d) = {%.6f, %.6f, 0};" % [point.id, point.x, point.y])

	file.store_line("")
	file.store_line("// Lines")
	for line: GGLine2D in lines:
		file.store_line("Line(%d) = {%d, %d};" % [line.id, line.start_point_id, line.end_point_id])

	file.close()
	return true


# -----------------------------------------------------------------------------
# Persistence (.ggb)
# -----------------------------------------------------------------------------

func save_document() -> bool:
	var save_path: String = "user://" + document_name
	var file: FileAccess = FileAccess.open(save_path, FileAccess.WRITE)
	if file == null:
		return false

	file.store_var(document_name)
	file.store_var(units)
	file.store_var(next_point_id)

	# Points block
	file.store_var(points.size())
	for point: GGPoint2D in points:
		file.store_var(point.id)
		file.store_var(point.x)
		file.store_var(point.y)

	# Lines block
	file.store_var(next_line_id)
	file.store_var(lines.size())
	for line: GGLine2D in lines:
		file.store_var(line.id)
		file.store_var(line.start_point_id)
		file.store_var(line.end_point_id)

	file.close()
	is_dirty = false
	return true


func load_document(doc_name: String) -> bool:
	var load_path: String = "user://" + doc_name + ".ggb"
	if not FileAccess.file_exists(load_path):
		return false

	var file: FileAccess = FileAccess.open(load_path, FileAccess.READ)
	if file == null:
		return false

	var loaded_document_name: String = String(file.get_var())
	var loaded_units: String = String(file.get_var())
	var loaded_next_point_id: int = int(file.get_var())

	var loaded_points: Array[GGPoint2D] = []
	var point_count_var: Variant = file.get_var()
	if point_count_var == null:
		file.close()
		return false
	var point_count: int = int(point_count_var)

	for _i: int in range(point_count):
		var p_id: int = int(file.get_var())
		var px: float = float(file.get_var())
		var py: float = float(file.get_var())
		loaded_points.append(GGPoint2D.new(p_id, px, py))

	var loaded_next_line_id: int = 1
	var loaded_lines: Array[GGLine2D] = []

	# Совместимость: если файл содержит блок линий, считываем его
	if file.get_position() < file.get_length():
		var next_line_var: Variant = file.get_var()
		if next_line_var != null:
			loaded_next_line_id = int(next_line_var)
			var line_count_var: Variant = file.get_var()
			if line_count_var != null:
				var line_count: int = int(line_count_var)
				for _j: int in range(line_count):
					var l_id: int = int(file.get_var())
					var p_start: int = int(file.get_var())
					var p_end: int = int(file.get_var())
					loaded_lines.append(GGLine2D.new(l_id, p_start, p_end))

	file.close()

	document_name = loaded_document_name
	units = loaded_units
	next_point_id = loaded_next_point_id
	next_line_id = loaded_next_line_id
	points = loaded_points
	lines = loaded_lines
	is_dirty = false

	return true
